Mitsubishi.UI/Controllers/ManualController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Mitsubishi.UI.Models;
using Mitsubishi.UI.Models.Entities;
using Mitsubishi.UI.Models.Services;
using System.Text;
using System.Text.RegularExpressions;

using System.Net;


using PagedList; 

namespace Mitsubishi.UI.Controllers
{
    public class ManualController : Controller
    {
       
        // GET: Publish/Manual
        public ActionResult Index()
        {

            string str = "";

            ViewBag.Url = "http://mitsubishi-electric.vn/so-tay-gia-dung.htm";

           

            if (this.Request.QueryString["s"] != "" && Request.QueryString["s"] != null)
            {
               // var c_page = this.Request.QueryString["page"];
               // str = this.Request.QueryString["s"];
               // int t_page = 1;
               // if (c_page != null)
                //{
                //    t_page = int.Parse(c_page);
                //}

               // var filteredItems = new ManualController().GetListItemBySearch(str, t_page);

               return View();
            }
            else
            {
              //  var c_page = this.Request.QueryString["page"];
               // int t_page = 1;
              //  if (c_page != null)
              //  {
               //     t_page = int.Parse(c_page);
               // }
               // var lst2 = new ManualController().GetListItemByCategory(str, t_page);

                return View();
            }

           
        }

        public ActionResult Playlist()
        {
            return View();
        }

        public ActionResult SotayFaq()
        {
            return View();
        }

        //gửi email hỏi đáp
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SendEmail(string name, string email, string question)
        {
            var result = false;
            var title = "Sổ tay gia dụng";

            var sb = new StringBuilder();
            sb.Append("<table width='100%;' cellspacing='3' cellpadding='3'>");
            sb.Append("<tr><td style='width:120px;'>Chuyên mục</td><td><h2>Sổ tay gia dụng</h2></td>");
            sb.Append("<tr><td style='width:120px;'>Họ tên</td><td>" + name + "</td>");
            sb.Append("<tr><td style='width:120px;'>Email</td><td>" + email + "</td>");
            sb.Append("<tr><td style='width:120px;'>Câu hỏi</td><td>" + question + "</td>");
            sb.Append("</table>");
            result = Utils.SendTipQuestion(email , title, sb.ToString());


            //true 
             return Json(result,JsonRequestBehavior.AllowGet);
            
           
            /*
            var message = new MailMessage();
            message.To.Add(new MailAddress(ConfigurationManager.AppSettings["ToEmail"]));  // replace with valid value 
            message.From = new MailAddress(ConfigurationManager.AppSettings["UserEmail"]);  // replace with valid value
            message.Subject = ConfigurationManager.AppSettings["SubjectEmail"];
            message.Body = body;
            message.IsBodyHtml = true;


            var smtp = new SmtpClient();
           
                var credential = new NetworkCredential
                {
                    UserName = ConfigurationManager.AppSettings["UserEmail"],
                    Password = ConfigurationManager.AppSettings["PassEmail"]
                };
                smtp.Credentials = credential;
                smtp.Host = ConfigurationManager.AppSettings["HostEmail"];
                smtp.Port = int.Parse(ConfigurationManager.AppSettings["PortEmail"]);
                
                smtp.EnableSsl = true;
                smtp.SendMailAsync(message);
             * */
               
        }

        public ActionResult Autocomplete_Search(string term)
        {
            //tìm kiếm ajax, tìm trong title và description
            IEnumerable<ManualContentEntity> lst = new ManualService().GetListAll();
            var filteredItems = lst.Where(s =>
                RemoveSign4VietnameseString(s.Title).ToLower().Contains(RemoveSign4VietnameseString(term).ToLower())).Select(w => w).Take(3).ToList();

            IList<SelectListItem> List = new List<SelectListItem>();
            foreach (ManualContentEntity e in filteredItems)
            {
                var url = Url.RouteUrl("ManualDetail", new
                {
                    title = Utils.ConvertUrf8ToAscii(e.Title),
                    itemId = e.ItemID
                });

                List.Add(new SelectListItem { Text = e.Title, Value = url});
            }

            return Json(List, JsonRequestBehavior.AllowGet);
        }



        public List<ProductCategoryEntity> GetListProductByCatId(int catId, int count)
        {

            var lst = new ProductCategoryService().GetListActive(catId, count);

            return lst;
        }

        public List<ManualCategoryEntity> GetListRoot()
        {
            var lst = new ManualCategoryService().GetListRoot();
            return lst;
        }
       
        public ActionResult ManualDetail()
        {
            var tmp = new ManualCategoryEntity();
            //Mặc định lấy Parent = 0
            int str = 0;
            if (RouteData.Values["itemId"] != null)
            {
                str = int.Parse(RouteData.Values["itemId"].ToString());

            }

           
            var item = new ManualService().GetItem(str);

            var url = Url.RouteUrl("ManualDetail", new
            {
                title = Utils.ConvertUrf8ToAscii(item.Title),
                itemId = item.ItemID
            });

            ViewBag.Url = "https://mitsubishi-electric.vn" + url;

            var des = item.LongDescription;

            des = Regex.Replace(des, "<.*?>", string.Empty).Trim();

            if (des.Length > 250) ViewBag.Description = des.Substring(0, 250);
            else ViewBag.Description = des;

            return View(item);
        }

        public ActionResult ListItemManual()
        {            
            return View();
        }

        public PagedList.IPagedList<ManualContentEntity> GetListItemByCategory(String str, int? page, string ManualCategoryExtraID, int Isvideo = 0)
        {
            var lst = new ManualService().GetList(str, 0, ManualCategoryExtraID, Isvideo);
            int pageSize = 13 ;
            int pageNumber = (page ?? 1);

            return lst.ToPagedList(pageNumber , pageSize );
            //return lst;
        }



        public ActionResult GetListItemByCategory_Ajax(string termID, int? page , string ManualCategoryExtraID)
        {
            var lst = new ManualService().GetList(termID, 0,  ManualCategoryExtraID);
           // int pageSize = 6;
           // int pageNumber = (page ?? 1);

          //  return lst.ToPagedList(pageNumber, pageSize);
            //return lst;

            var html = "<div class=\"top-item-article\">";
            foreach (var item in lst)
            {
                var title = item.Title;

                Regex regex2 = new Regex(" ");
                string[] substrings2 = regex2.Split(title);
                string tmp2 = "";

                foreach (string match in substrings2)
                {

                    tmp2 += match + " ";
                    if (tmp2.Length > 35)
                    {
                        tmp2 += "...";
                        break;
                    }
                }
                title = tmp2;                
                
                var url = Url.RouteUrl("ManualDetail", new
                {
                    title = Utils.ConvertUrf8ToAscii(title),
                    itemId = item.ItemID
                });

                var des = Regex.Replace(item.LongDescription, "<.*?>", string.Empty).Trim();
                des = HttpUtility.HtmlDecode(des);

                Regex regex = new Regex(" ");
                string[] substrings = regex.Split(des);
                string tmp = "";
               
                foreach (string match in substrings)
                {
                    
                    tmp += match + " ";
                    if (tmp.Length > 90)
                    {
                        tmp += "...";
                        break;
                    }
                }
                des = tmp;
                
              //  if (des.Length > 90)
               // {
                    
               //     des = des.Substring(0, 90) + "...";
               // }


                html += "<div class=\"col-md-4 col-sm-6 col-xs-12 item-manual\">";
                html += "<div class=\"thumbnail-item\">";
                html += "   <a href=\"" + url + "\"><img src=\"/images/sotaygiadung/" + @item.Thumbnail + "\" title=\"" + title + "\" alt=\"" + title + "\"><span class=\"hover-element-article\"></span></a>";
                html += "</div>";
                html += "<div class=\"\">";
                html += "<p class=\"cat-label\">" + @item.Category.Title + "</p>";
                html += "     <h2 class=\"title-manual\"><a  href=\"" + url + "\">" + title + "</a></h3>";
                html += "<p class=\"createDate\">"+string.Format("{0:dd/MM/yyyy}", item.CreatedDate)+"</p>";
                html += "    <p class=\"description\">" + des + "";
                html += " </div>";
                html += "<div class=\"clear\"></div>";
                html += "</div>";

            }
            html += "<div class=\"clear\"></div>";
            html += "</div>";


            return Json(html, JsonRequestBehavior.AllowGet);
        }


        public List<ManualContentEntity> Related( int count, int exclude , int catID)
        {
            var lst = new ManualService().GetListRelated(exclude, count, catID);
            return lst;

        }
    

Mitsubishi.UI/Controllers/SystemConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mitsubishi.UI.Controllers
{
    public class SystemConfigController : Controller
    {
        private Models.Digi digicontext = new Models.Digi();
        // GET: SystemConfig
        public ActionResult Index()
        {            
            return View();
        }

        public void getconfig()
        {
            if (HttpRuntime.Cache.Get("__configs") != null)
            {
                ViewBag.__configs = HttpRuntime.Cache.Get("__configs");
            }
        }
    }
}

Mitsubishi.UI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Mitsubishi CORPORATION</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/kendo/css")
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendo")
    <script src="~/Scripts/Mitsubishi.js"></script>
    <link href="~/Content/prettyPhoto.css" rel="stylesheet" type="text/css" media="screen" title="prettyPhoto main stylesheet" />
    <script type="text/javascript" src="~/Scripts/jquery.prettyPhoto.js"></script>

    @{ var culture = System.Threading.Thread.CurrentThread.CurrentCulture.ToString(); }
    <script src="@Url.Content("~/Scripts/kendo/cultures/kendo.culture.en.min.js")"></script>

    @* Set the current culture *@
    <script>
        kendo.culture("@culture");

        $(document).ready(function () {
            $(".gallery:first a[rel^='prettyPhoto']").prettyPhoto(
            {
                animation_speed: 'fast',
                deeplinking: false,
                theme: 'pp_default',
                slideshow: 3000,
                autoplay_slideshow: false
            });
        });
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mitsubishi", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        @Html.ActionLink("Product Category", "Index", "ProductCategory")
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                            <li>@Html.ActionLink("Merchant", "Index", "Merchant")</li>
                            <li>@Html.ActionLink("Comment", "Index", "Comment")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Content", "Index", "Content")</li>
                    <li class="dropdown">
                        @Html.ActionLink("Sổ tay", "Index", "Manual")
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                            <li>@Html.ActionLink("FAQ", "Index", "Faq")</li>
                            <li>@Html.ActionLink("Video", "Index", "Video")</li>
                            <li>@Html.ActionLink("Activation", "Index", "Activation")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Inquiry", "Index", "Inquiry")</li>
                    <li>@Html.ActionLink("Careers", "Index", "Careers")</li>
                    <li>@Html.ActionLink("Agency", "Index", "Agency")</li>
                   
                   
                    <li class="dropdown">@Html.ActionLink("System Config", "Index", "SystemConfig")
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                            <li>@Html.ActionLink("Banner", "Index", "Banner")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mitsubishi Corporation</p>
        </footer>
    </div>
</body>
</html>

Mitsubishi.UI/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>*@

    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Mitsubishi.UI/Areas/Admin/Views/Shared/_LayoutAdminDigi.cshtml
@using Microsoft.AspNet.Identity
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ADMIN MITSUBISHI</title>
    <link href="~/Areas/Admin/Css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Css/Login/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Css/Admin-Digi.css" rel="stylesheet" />

    @Styles.Render("~/Content/kendo/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendo")

    <link href="~/Areas/Admin/Css/jquery-ui.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/jquery.prettyPhoto.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @{ var culture = System.Threading.Thread.CurrentThread.CurrentCulture.ToString(); }
    <script src="@Url.Content("~/Scripts/kendo/cultures/kendo.culture.en.min.js")"></script>

    @* Set the current culture *@
    <script>
        kendo.culture("@culture");

        $(document).ready(function () {
            $(".gallery:first a[rel^='prettyPhoto']").prettyPhoto(
            {
                animation_speed: 'fast',
                deeplinking: false,
                theme: 'pp_default',
                slideshow: 3000,
                autoplay_slideshow: false
            });
        });
    </script>
</head>
<body>
    <div class="topmenu">
        <h1 class="logo-text pull-left"><a target="_blank" href="@Url.Content("~/")"><i class="fa fa-home" aria-hidden="true" style="padding: 0px 5px 0px 0px;"></i>Mitsubishi</a></h1>
        <div class="pull-right top-right">
            @Html.ActionLink("Hi! " + User.Identity.GetUserName(), "Manage", "Account", routeValues: null, htmlAttributes: new { title = "Administrator" })
            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out" aria-hidden="true" style="font-size: 19px;"></i></a>
                }
            }
        </div>
    </div>
    
        <div class="left pull-left col-md-2">
            <ul class="lv1">
                <li class="active">
                    <a href="@Url.Content("~/Admin/Home/Index")">
                        <i class="fa fa-tachometer" aria-hidden="true"></i>
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#sanpham">
                        <i class="fa fa-cube" aria-hidden="true"></i>
                        Sản phẩm
                        <ul class="collapse lv2" id="sanpham">
                            <li><a href="#">Danh mục sản phẩm</a></li>
                            <li><a href="@Url.Content("~/Admin/ProductCategory")">Sản phẩm</a></li>
                        </ul>
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#baiviet">
                        <i class="fa fa-book" aria-hidden="true"></i>
                        Bài viết
                        <ul class="collapse lv2" id="baiviet">
                            <li><a href="#">Danh mục</a></li>
                            <li><a href="@Url.Content("~/Admin/Content")">Bài viết</a></li>
                        </ul>
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Merchant")">
                        <i class="fa fa-bookmark" aria-hidden="true"></i>
                        Merchant
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Comment")">
                        <i class="fa fa-comments" aria-hidden="true"></i>
                        Comment
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Manual")">
                        <i class="fa fa-tag" aria-hidden="true"></i>
                        Sổ tay
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Faq")">
                        <i class="fa fa-question" aria-hidden="true"></i>
                        FAQ
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Video")">
                        <i class="fa fa-video-camera" aria-hidden="true"></i>
                        Video
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Activation")">
                        <i class="fa fa-calendar" aria-hidden="true"></i>                        
                        Activation
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Inquiry")">
                        <i class="fa fa-hand-rock-o" aria-hidden="true"></i>
                        Inquiry
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Careers")">
                        <i class="fa fa-user-plus" aria-hidden="true"></i>
                        Tuyển dụng
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Agency")">
                        <i class="fa fa-globe" aria-hidden="true"></i>
                        Agency
                    </a>
                </li>
                <li>
                    <a href="@Url.Content("~/Admin/Banner")">
                        <i class="fa fa-camera" aria-hidden="true"></i>
                        Banner
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#user">
                        <i class="fa fa-users" aria-hidden="true"></i>
                        User
                        <ul class="collapse lv2" id="user">
                            <li><a href="@Url.Content("~/Admin/Account/ListUsers")">Tất cả user</a></li>
                            <li><a href="@Url.Content("~/Admin/Account/AddUser")">Thêm user</a></li>
                        </ul>
                    </a>
                </li>                
                <li>
                    <a href="@Url.Content("~/Admin/SystemConfig")">
                        <i class="fa fa-cog" aria-hidden="true"></i>
                        Cấu hình hệ thống
                    </a>
                </li>
                
            </ul>
        </div>
        <div class="right pull-right col-md-10">
            @RenderBody()
        </div>
    <script src="~/Areas/Admin/Js/bootstrap.js"></script>
    <script>
        var h = window.innerHeight;
        //alert(h);
        jQuery(".left").css("height", h);
    </script>
</body>
</html>