Mitsubishi.UI/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mitsubishi.UI.Controllers
{
    public class SearchController : Controller
    {
        //
        // GET: /Publish/Search/
        public ActionResult Index()
        {
            return View();
        }
	}
}

Mitsubishi.UI/Views/Search/Index.cshtml
@using Mitsubishi.UI.Controllers
@{
    ViewBag.Title = "Mitsubishi Electric";
    Layout = "~/Views/Shared/_LayoutSearch.cshtml";
}


    <div class="service-container container">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">            
            <h2>Kết quả tìm kiếm  </h2>
            </div>
        <div class="clear"></div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="section">
                    <div class="searchForm">
                        <input class="searchText" id="criteria2">
                        <input class="btn-search" id="search2" value="@HomeController.GetTextValue("Home_ButtonGo")" type="button">
                    </div>
                </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="Result-list container" style="margin:30px 0">
            <script>
                (function () {
                    var cx = '013741694915874451447:sgh_gcns5a8';
                    var gcse = document.createElement('script');
                    gcse.type = 'text/javascript';
                    gcse.async = true;
                    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                        '//cse.google.com/cse.js?cx=' + cx;
                    var s = document.getElementsByTagName('script')[0];
                    s.parentNode.insertBefore(gcse, s);
                })();
            </script>
            <gcse:searchresults-only></gcse:searchresults-only>

        </div>
        <script>
            $(document).ready(function () {
                var criteria = '@Server.HtmlDecode(Request.QueryString["q"])';

                $('#criteria2').val(criteria);

                $('#criteria2').keypress(function (e) {
                    if (e.keyCode == 13) {
                        criteria = $('#criteria2').val();
                        var url = '@Url.Action("Index", "Search")' + '?q=' + criteria;

                        $(location).attr('href', url);
                    }
                });

                $('#search2').click(function () {
                    criteria = $('#criteria2').val();
                    var url = '@Url.Action("Index", "Search")' + '?q=' + criteria;

                    //window.location.href = url;
                    $(location).attr('href', url);
                });
            });
        </script>